Converting Splash layout to constraint layout
Vishwajith-Shettigar/NextGen pull request #129
Opened 2024-10-25 18:49 UTC by Darkeye14

issue number #81 
Migrated from the traditional linear layout for the splash screen to Constraint Layout.
No major changes have been made and some minor warnings have been addressed.
The UI features are preserved and no changes have been made.
 
## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

 ## Screenshot of successful build.
![Screenshot 2024-10-25 231538](https://github.com/user-attachments/assets/efdb0769-645c-4bb9-a43c-ad9d245ad84e)

Before changes :
![Screenshot 2024-10-25 230723](https://github.com/user-attachments/assets/246be6f7-a831-4d4a-a9fb-a6e65c9b2db0)

After Changes:
![Screenshot 2024-10-25 231611](https://github.com/user-attachments/assets/5832dfbb-0e7a-4102-ae4e-acd552b92bd1)

## Screenshots / Screen Recordings
https://github.com/user-attachments/assets/a2873bdd-d8e5-4e0b-81a6-137979278673

2024-10-26 05:48 UTC, Darkeye14 commented
@Vishwajith-Shettigar there are still some layouts which have not been implemented completely and but are still  using relative layouts. Do you want me to migrate them to constraint Layouts??

2024-10-27 05:50 UTC, Vishwajith-Shettigar requested changes

2024-10-27 05:50 UTC, Vishwajith-Shettigar commented on app/src/main/res/layout/activity_splash_screen.xml
> +</androidx.constraintlayout.widget.ConstraintLayout>
Add an extra empty line at EOF.

2024-10-27 05:50 UTC, Vishwajith-Shettigar commented on app/src/main/res/values/strings.xml
>  </resources>
Add an extra empty line at EOF.

2024-10-27 05:51 UTC, Vishwajith-Shettigar commented
> @Vishwajith-Shettigar there are still some layouts which have not been implemented completely and but are still using relative layouts. Do you want me to migrate them to constraint Layouts??

Okay.

2024-10-27 17:48 UTC, Darkeye14 commented on app/src/main/res/values/strings.xml
>  </resources>
okay!

2024-10-27 17:56 UTC, Darkeye14 commented
Done Sir!!

2024-10-29 03:50 UTC, merged