Changed user circle color to blue with low opacity.
Vishwajith-Shettigar/NextGen pull request #133
Opened 2024-10-28 10:54 UTC by LegendCK

## Description
Please include issue number and a summary of the change.

## Checklist:
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

 ## Screenshot of successful build.
![image](https://github.com/user-attachments/assets/957e7690-22b0-45bd-aac5-88829de1bb37)

## Screenshots / Screen Recordings
This should be the color which i have updated.
![image](https://github.com/user-attachments/assets/61f911bd-2cdc-4ca6-b88d-291f4636c297)

## Note: Only ask for review when you complete all above.

2024-10-28 10:55 UTC, LegendCK commented
Can you just check and tell me whether it worked. Cause I not having Google maps API key, due to which i am not able check with maps. 

If there's any changes to perform, let me know.

2024-10-29 03:52 UTC, Vishwajith-Shettigar commented
@LegendCK also remove the black stroke.

2024-10-29 03:58 UTC, Vishwajith-Shettigar requested changes

2024-10-29 03:58 UTC, Vishwajith-Shettigar commented on app/src/main/java/com/example/nextgen/nearby/NearByFragment.kt
> +        .fillColor(Color.argb(51, 72, 133, 237))
Use this color from colors file.

2024-10-29 05:18 UTC, LegendCK commented on app/src/main/java/com/example/nextgen/nearby/NearByFragment.kt
> +        .fillColor(Color.argb(51, 72, 133, 237))
@Vishwajith-Shettigar  Check now.

2024-10-29 10:35 UTC, Vishwajith-Shettigar commented
Thanks @LegendCK .

2024-10-29 10:35 UTC, merged

2024-10-29 19:07 UTC, LegendCK commented
> Thanks @LegendCK .

Happy to help.