Enhanced README with Troubleshooting Section 🛠️
Vishwajith-Shettigar/NextGen pull request #89
Opened 2024-10-11 13:16 UTC by vaishnavipal1869

## Description #80 
- The **addition of the troubleshooting section** aims to enhance the user experience by providing immediate solutions to common problems encountered while using the app. This **proactive approach** empowers users to troubleshoot issues independently, thereby reducing frustration and the need for support inquiries.

## Checklist:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

## Screenshot of successful build.
- Unfortunately, I do not have a screenshot of the successful Gradle build as my contribution was focused on improving documentation.

## Screenshots / Screen Recordings
- Please refer to the updated README for the troubleshooting section.

## Request for Review
- I believe I have completed all the required steps for this pull request. I would greatly appreciate it if you could take a moment to review my changes and provide your feedback. Thank you!

2024-10-12 04:06 UTC, Vishwajith-Shettigar requested changes
In troubleshooting section, only add some common build failures contributors face.

2024-10-12 04:06 UTC, Vishwajith-Shettigar commented on README.md
> +### 1. App Crashes on Device Configuration Changes
This shouldn't be in Troubleshooting section.

2024-10-12 04:06 UTC, Vishwajith-Shettigar commented on README.md
> +### 3. Profile Pictures Still Visible Despite Disabling
This is an issue which will be resolved soon. Putting it in this section doesn't make any sense ig.

2024-10-12 04:06 UTC, Vishwajith-Shettigar commented on README.md
> +### 4. Red Stroke Not Showing in Default Image on Map
Same here.

2024-10-12 04:06 UTC, Vishwajith-Shettigar commented on README.md
> +### 5. Online Status Not Working Properly
Same here

2024-10-12 04:20 UTC, Vishwajith-Shettigar commented
@vaishnavipal1869  you can add below to troubleshooting guide.

https://github.com/Vishwajith-Shettigar/NextGen/issues/75#issuecomment-2408345836

https://github.com/Vishwajith-Shettigar/NextGen/issues/75#issuecomment-2406603579 ( Please have a quick chat with @MiRa202321 to understand the problem and solution she came up with.

https://github.com/Vishwajith-Shettigar/NextGen/discussions/47#discussion-7274929

2024-10-12 05:40 UTC, vaishnavipal1869 commented
I can incorporate the requested changes and make adjustments as needed.
Should I proceed with that?

On Sat, Oct 12, 2024, 9:36 AM Vishwajith Shettigar ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> In troubleshooting section, only add some common build failures
> contributors face.
> ------------------------------
>
> In README.md
> <https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545554>
> :
>
> > @@ -41,6 +41,46 @@ Interact with people within a 100-meter radius! Get real-time locations of nearb
>
>  Time to mingle, chat, and rate! Have fun exploring the world around you. 🌍🎉
>
> +## Troubleshooting 🤔
> +
> +If you encounter any issues while using the app, this section will help you find quick solutions to common problems.
> +
> +### 1. App Crashes on Device Configuration Changes
>
> This shouldn't be in Troubleshooting section.
> ------------------------------
>
> In README.md
> <https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545800>
> :
>
> > +
> +If you encounter any issues while using the app, this section will help you find quick solutions to common problems.
> +
> +### 1. App Crashes on Device Configuration Changes
> +**Issue:** The app crashes when the device orientation or configuration changes.
> +**Solution:**
> +- Ensure that `android:configChanges="orientation|screenSize"` is added in the AndroidManifest.xml for the affected activities.
> +- Consider using ViewModel or handling configuration changes appropriately in the activity lifecycle.
> +
> +### 2. User's Location is Not Detected
> +**Issue:** The app is not able to detect the user's location.
> +**Solution:**
> +- Make sure that location permissions are granted in the device settings.
> +- If the location is off, prompt the user to enable location services.
> +
> +### 3. Profile Pictures Still Visible Despite Disabling
>
> This is an issue which will be resolved soon. Putting it in this section
> doesn't make any sense ig.
> ------------------------------
>
> In README.md
> <https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545820>
> :
>
> > +- Ensure that `android:configChanges="orientation|screenSize"` is added in the AndroidManifest.xml for the affected activities.
> +- Consider using ViewModel or handling configuration changes appropriately in the activity lifecycle.
> +
> +### 2. User's Location is Not Detected
> +**Issue:** The app is not able to detect the user's location.
> +**Solution:**
> +- Make sure that location permissions are granted in the device settings.
> +- If the location is off, prompt the user to enable location services.
> +
> +### 3. Profile Pictures Still Visible Despite Disabling
> +**Issue:** Profile pictures are still visible on the map or chat screen, even after setting them to be disabled.
> +**Solution:**
> +- Check the API response to ensure that the `profilePictureVisible` flag is properly updated.
> +- Ensure that the visibility logic is correctly handled in the frontend component.
> +
> +### 4. Red Stroke Not Showing in Default Image on Map
>
> Same here.
> ------------------------------
>
> In README.md
> <https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545850>
> :
>
> > +- Make sure that location permissions are granted in the device settings.
> +- If the location is off, prompt the user to enable location services.
> +
> +### 3. Profile Pictures Still Visible Despite Disabling
> +**Issue:** Profile pictures are still visible on the map or chat screen, even after setting them to be disabled.
> +**Solution:**
> +- Check the API response to ensure that the `profilePictureVisible` flag is properly updated.
> +- Ensure that the visibility logic is correctly handled in the frontend component.
> +
> +### 4. Red Stroke Not Showing in Default Image on Map
> +**Issue:** Red stroke does not appear in the default image on the map.
> +**Solution:**
> +- Check if the image loading logic is correctly implemented in the Map component.
> +- Ensure that the red stroke is added as an overlay when the map is rendered.
> +
> +### 5. Online Status Not Working Properly
>
> Same here
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vishwajith-Shettigar/NextGen/pull/89#pullrequestreview-2363733262>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BLE4TM6SHOPS4BQRR4CYIT3Z3CN4BAVCNFSM6AAAAABPY5EPNKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNRTG4ZTGMRWGI>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-10-12 05:48 UTC, MiRa202321 commented
@vaishnavipal1869 Hi there! I had to ask that why is the map blank? Can it be because of some fault while setting up? I have allowed the permissions to access my location. Also, I have added the map's api.
![Screenshot 2024-10-12 111458](https://github.com/user-attachments/assets/23892755-461a-4957-9487-e4333ef74ae2)

2024-10-12 06:12 UTC, Vishwajith-Shettigar commented
> @vaishnavipal1869 Hi there! I had to ask that why is the map blank? Can it be because of some fault while setting up? I have allowed the permissions to access my location. Also, I have added the map's api. ![Screenshot 2024-10-12 111458](https://private-user-images.githubusercontent.com/123196933/375929192-23892755-461a-4957-9487-e4333ef74ae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MTI5MjIsIm5iZiI6MTcyODcxMjYyMiwicGF0aCI6Ii8xMjMxOTY5MzMvMzc1OTI5MTkyLTIzODkyNzU1LTQ2MWEtNDk1Ny05NDg3LWU0MzMzZWY3NGFlMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwNTU3MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGRiZWJlOTE2NGFiODMzYTExN2VkMDI1ZGY1ZDlmMzA0NWU4YTVkZDUxYzY5ZDFhYTcxY2IwMmU2YmEwZTczJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.lm9QO8vnxsNLlJeGsVCsHA95962j-vTQDvt2lrGu2CY)

Reinstall and give all permissions, and turn on device location. It should work

2024-10-12 06:28 UTC, vaishnavipal1869 commented
@Vishwajith-Shettigar,

Hello! I have made the requested changes to the README file. However, I don’t see an option to create a new pull request. Could you please advise on how to proceed?

Thank you!

2024-10-14 02:13 UTC, Vishwajith-Shettigar commented
> ![image](https://private-user-images.githubusercontent.com/180996531/375931865-dd47e2f0-833c-4192-9548-765ee2747096.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg4NzIxOTMsIm5iZiI6MTcyODg3MTg5MywicGF0aCI6Ii8xODA5OTY1MzEvMzc1OTMxODY1LWRkNDdlMmYwLTgzM2MtNDE5Mi05NTQ4LTc2NWVlMjc0NzA5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNFQwMjExMzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMDUwNTMzYTE1NWY3ZjUxYzMwZmI3YzNiNmZhMmIzZWMwOTVlODBmZjY1YWNmNjQxMTc4ZjVjYjZlNTc1MjZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1Kx16cLAJbcvXaMyk10dbG3EkCt_FmqrPhSjGQ6e2mo)
> 
> @Vishwajith-Shettigar,
> 
> Hello! I have made the requested changes to the README file. However, I don’t see an option to create a new pull request. Could you please advise on how to proceed?
> 
> Thank you!

You dont need to create new PR !

2024-10-14 17:26 UTC, vaishnavipal1869 commented
hey @Vishwajith-Shettigar can you please look into the updated readme and assign me with the points???

2024-10-15 03:05 UTC, Vishwajith-Shettigar commented
> @vaishnavipal1869 you can add below to troubleshooting guide.
> 
> [#75 (comment)](https://github.com/Vishwajith-Shettigar/NextGen/issues/75#issuecomment-2408345836)
> 
> [#75 (comment)](https://github.com/Vishwajith-Shettigar/NextGen/issues/75#issuecomment-2406603579) ( Please have a quick chat with @MiRa202321 to understand the problem and solution she came up with.
> 
> [#47 (comment)](https://github.com/Vishwajith-Shettigar/NextGen/discussions/47#discussion-7274929)

Please add the above to the troubleshooting guide and retain the rest of the old troubleshooting guide, except for the parts I mentioned https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545554 , https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545800, https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545820 , https://github.com/Vishwajith-Shettigar/NextGen/pull/89#discussion_r1797545850

2024-10-15 17:42 UTC, vaishnavipal1869 commented
@MiRa202321 can you please explain the problem and the solution you came up with

2024-10-17 15:05 UTC, vaishnavipal1869 commented
hello sir @Vishwajith-Shettigar could you please review the requested chnages?, thank you!!

2024-10-17 15:27 UTC, Vishwajith-Shettigar reviewed
https://github.com/Vishwajith-Shettigar/NextGen/discussions/47  add this.

2024-10-17 15:27 UTC, Vishwajith-Shettigar commented on README.md
> +### 5. Network Issues
Remove this.

2024-10-17 16:04 UTC, vaishnavipal1869 commented
@Vishwajith-Shettigar is this okay now ?

2024-10-18 02:17 UTC, Vishwajith-Shettigar commented on README.md
> +You can find the repository for reference [here](https://github.com/Vishwajith-Shettigar/video-call-server-node.js).
Repeated sentence.

2024-10-18 02:18 UTC, Vishwajith-Shettigar commented on README.md
> +You can find the repository for reference [here](https://github.com/Vishwajith-Shettigar/video-call-server-node.js).
you can find the repository for reference.
You can find the repository for reference [here]

2024-10-19 16:24 UTC, vaishnavipal1869 commented
@Vishwajith-Shettigar sir i have successfully removed the duplicate sentence, would you please look into it.

2024-10-20 03:40 UTC, Vishwajith-Shettigar commented
Thanks @vaishnavipal1869

2024-10-20 03:40 UTC, merged